name: pipeline-basico

on:
  push:
    branches: 
      workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Executa comando
        run: echo "Configuração inicial do pipeline"
